### PR TITLE
:bug: open links in a new tab by default (#955)

### LINKED ISSUE #955: When reviewing talks, open links in a new window by default
When reviewing a talk, clicking a link replaces the current page. That would be ok-ish but the real issue is that navigating back to the reviewing page (for an example https://conference-hall.io/organizer/event/Jnevkv3bLyxZOyYyiWSC/proposals/0MQhyhydqFqiJuDxBEnl?) looses the prev/next context.

Would it be possible to always open links in new windows?

### PR DESCRIPTION
**Pull request by mflagey**
This pull request add an eventListener to open links in new tab when organizers are reviewing a proposal.

Closes #955

### CODE REVIEW

**Comment by bpetetot** [comment]
Hi @mflagey. Thanks a lot for the PR.
I have to check, but I think this is something we may be able to handle directly with the markdown parser (`marked`) by customising the renderer. We might avoid handling it with Js listeners.

**Comment by mflagey** [comment]
Ok , I will try with custom renderer !

**Comment by mflagey** [comment]
@bpetetot I tried something with custom renderer. This requires changing the expected result in unit tests because renderer adds the target="_blank" property to the anchors.

**Comment by bpetetot** [comment]
Thanks a lot @mflagey!
Seems good to me, I made a small change in order to avoid instanciating the renderer inside the component.

**Pull request merged**
