### PR TITLE
:sparkles: email.to.all.organisators.by.config

### LINKED ISSUE #462: [organizer] Add mail on organization configuration to send events
Based on #348 instead of sending a mail to each organizers, just send one mail to an organization contact mail address.

And configure if notification should be sended to :  
- every organizers
- organization contact mail
- both

### PR DESCRIPTION
**Pull request by corinnekrych**
Fixes https://github.com/bpetetot/conference-hall/issues/462 
This PR revisits email sending to organizers' email and/or conference's contact email.
- send all email to speakers
- send emails as cc to contact email if `contact` and `conference mailing list` fields in event's configuration page are set.
- send emails as bcc to orgas' emails if `email` is specified in orga's profile and `private orgas' emails` field in event's configuration page is true.

We can go one step further and add a field to configure ending email to speakers. Atm all mails are send to speakers.
> NOTE: the saas version https://conference-hall.io/ will still work but the default will be changed. ie: emails will not be send to orgas and mailing list. I can add a small migration script as CF (if needed)

### CODE REVIEW

**Comment by bpetetot** [comment]
@corinnekrych I have just used the `tooltip` in label form made by @patou in a previous PR.

I have also sync this branch with master, so now the webapp and cloud functions uses **node 10** and you need to update dependencies with `yarn` command

**Comment by corinnekrych** [comment]
Perfect fine for me. if you approve it we''ll merge it.

**Comment by bpetetot** [comment]
Before merging it, I think it will be necessary to have a migration script for the SaaS version.
Because, meetup organizers won't received email notifications for new proposals if they don't change their event configuration.

**Comment by bpetetot** [comment]
I have made some updates:
- change attributes name in`event` document to:
```js
{
   sendEmailsTo: {
       contact: true,
       organizers: true,
   }
}
```
- be able to choose which email the organizers want to receive
- add a migration script for the saas version
- I restored "received emails" for organizers, to avoid confusion when an organizer received an email "Talk successfully submitted"
- set the configuration in the deliberation tab (this is when emails are sent)

Screenshot 2019-07-28 at 01 05 32

**Comment by bpetetot** [comment]
@corinnekrych Thanks for this feature ;)

**Pull request merged**
