### PR TITLE
:sparkles: revisit proposal page to decouple deliberation from email s…

### PR DESCRIPTION
**Pull request by corinnekrych**
…ending

Fixes:
* https://github.com/bpetetot/conference-hall/issues/508 
* https://github.com/bpetetot/conference-hall/issues/479

This PR does:
- [x] add an (optional) mailgun's webhook to mark email as delivered
- [x] modify cloud function `onUpdateProposal.js` to decouple email sending and state update
- [x] on proposal page, add a button select all, add a action button to send emails.
- [x] provide a way to refresh the proposal list page: webpush or polling or refresh
- [x] provide an option to send email again if not delivered

### CODE REVIEW

**Comment by corinnekrych** [comment]
Fixes https://github.com/bpetetot/conference-hall/issues/508

Here is a description on how to send 200 bulk emails with 197 rejected, 1 accepted, 2 still under deliberation:
- Select all pages, select all 200 proposal
- Mark them rejected with the global “Reject Proposals”
- Go to the one accepted mark it accepted via the individual proposal deliberation dropdown
- Select the two still under deliberation mark them “Deliberating”
If all proposals are still selected, go to global do button select “send emails”
MailGun has a limit of 100 emails per hour, as a result some emails will be delivered.
- At one point MailGun will send the email:
“Your account is on probation and domains are limited to 100 messages / hour. To maintain the rate the account has been temporarily disabled.
The account will be enabled in 7874 seconds.
Thank you, Mailgun Team”
Note no delivery error is sent but some of the proposals will keep the “sent” status without being “delivered”. Thanks to the dCF web hook, the delivered emails were marked delivered we know which one has been properly delivered.
- After 2h (according to MailGun notice), select all proposals and click global “send email” the email not delivered will be selected and mark again as sending therefore the CF “onProposalUpdate” will send them again.
- Hit the refresh button and see all delivered proposals

=> All emails are delivered

**Comment by corinnekrych** [comment]
@bpetetot here is a PR proposed to fix the issue of emails not being delivered.
Let me know what you think. I'll do a short recording of the feature once my mailgun is unlocked :)

We can improve te design with grouping all filters in one select like [react-select component](https://react-select.com/home) with multi select and groups. that could be done in a separate PR.

**Review by bpetetot — APPROVED** [review]
Great Job @corinnekrych !
Instead of writing some comment, I directly made changes ;)
You can review it commit by commit if you want.
I will go further in the tests, then I will merge it to production.
Thanks a lot

**Comment by bpetetot** [comment]
I have also sync this branch with master, so now the webapp and cloud functions uses **node 10** and you need to update dependencies with `yarn` command

**Comment by corinnekrych** [comment]
👍 looks all good for me.

**Pull request merged**
