### PR TITLE
✨ enable / disable automatic sending of deliberation emails

### PR DESCRIPTION
**Pull request by bpetetot**
### Description
Be able to enable / disable this feature in the event configuration page (some organizers prefer to contact speakers themself)

### CODE REVIEW

**Comment by bpetetot** [comment]
@corinnekrych you can check this if you want, it will be part of the final feature of deliberation emails

**Comment by corinnekrych** [comment]
👀

**Comment by corinnekrych** [comment]
@bpetetot the configuration works well (even got it deployed for RivieraDEV cfp)!

One thing tho, if you disable the automatic sending of emails, I think we need to revisit: [talkSelection.jsx](https://github.com/bpetetot/conference-hall/pull/343/files#diff-f121574ca60ac1cd694de1f2b343228cR8) to not be greyed out the deliberation. if no email is sent directly the conference organizer might want to have the option to accept then revisit their initial choice. 

wdyt?

**Comment by bpetetot** [comment]
@corinnekrych Yes that's a good idea, so I made it ;)
I also made some changes:
- In the cloud function trigger, I have added a check that prevents to go further if the proposal changes are not about the state and if the email was already sent.
- I have also changed the color of accepted and rejected states of the speaker talk.

**Comment by corinnekrych** [comment]
LGTM !

**Pull request merged**
