### PR TITLE
💥 Change email destination to 'bcc' rather than 'to'

### PR DESCRIPTION
**Pull request by HugoGresse**
Change the destination of the emails to bcc to not disclose destination email for everyone. Helpful for Montpellier where we have multiple meetups on the same CH. 

I've read the contributing guidelines a little late. Maybe you can add the gitmoji to the commit message when merging the PR.

### CODE REVIEW

**Comment by corinnekrych** [comment]
It's useful to have the email sent to co-speakers as a 'to' instead of 'cc'. so that as a speaker you know you co-speaker has been informed too :)
For organisation vs conference mailing list there is a ticket https://github.com/bpetetot/conference-hall/issues/462
@HugoGresse why can't you have different organisations defined in one common conference-hall. for each orga you can have a set of members. would that solve your issue?

**Comment by HugoGresse** [comment]
Understood for 'to' for speaker, maybe I can add an option for that to support both destination. 
About having different orga, Our current process is that every speaker submit to https://conference-hall.io/public/event/1rHdMuHF5OapZtWg9ICn and select the meetup they want to (optional). Can we have many organization managing one event? We don't want to have "Montpellier Android, Montpellier JUG, Montpellier DigData, ...", the list will be very long with 13+ meetup in montpellier under this CH.

**Comment by corinnekrych** [comment]
Interesting way of using conference-hall's talk categorie to select a meetup :)
I'd have done one orga + 13 events but true then the user will have to do 13 submissions.... We should have a multi-select dropdown to do several submission at once (I'll log a separate issue for it).

@HugoGresse check out this PR https://github.com/bpetetot/conference-hall/pull/574 which make sending to organizer configurable and always send as bcc.

**Comment by bpetetot** [comment]
Hi @HugoGresse thanks for your contribution, but I will take PR #574 done by @corinnekrych 
The PR #574 takes your requirements and more. Thanks again ;)

**Comment by HugoGresse** [comment]
Thanks for your help Corinne & Benjamin, I'll wait for #574 to be merged then!
<3

**Pull request closed without merging**
