### PR TITLE
:sparkles: Add language field

### PR DESCRIPTION
**Pull request by brunosabot**
Hello,

This pull request add one optional field on a user talk :
 - The talk language, since some abstracts (at BDX I/O) are in english but will eventually be french on the event day.

### CODE REVIEW

**Comment by frinyvonnick** [comment]
@brunosabot what do you think about using a type "conference with livecoding" ?

**Comment by frinyvonnick** [comment]
image

I'm talking about "talk formats" like on the picture 😄

**Comment by bpetetot** [comment]
@brunosabot Thanks for this PR 🙏, sorry I'm a little late to review it 

### The language field
You're right that the language is a necessary field to a talk. But I would prefer to have a list of languages and maybe a multiple selection choice. Because, maybe a speaker could give a talk in english and french.

### The live-coding field
I think that I will not take this change, because is too specific to a talk format (managed by the event). Instead, we may should give the ability to organizer to add specific field at the submission moment, or change the "reference" field of a talk to give more info.

**Comment by bpetetot** [comment]
@brunosabot Thanks, I have made some little changes with:
- display language in a badge
- add language in proposal page for organizers
- add language in API and proposals list exports

**Pull request merged**
