### PR TITLE
:sparkles: add private events

### LINKED ISSUE #350: Create a private event
Be able to create a private.
The event will not be searchable when submitting a talk
You must have the event link to submit a talk

### PR DESCRIPTION
**Pull request by bpetetot**
Closes #350

### CODE REVIEW

**Comment by frinyvonnick** [comment]
So private events are only for organizers ?

**Review by frinyvonnick — APPROVED** [review]
👍

**Review by nlepage — APPROVED** [review]

**Review by hgwood — COMMENTED** [review]
I have questions :)

- how can I access the page for the private event I created?
- if I know the URL, can I still access a private event page?
- the filter that removes private events for the list looks like it lives in the front-end, which means I can override it if I want to; is that OK?

**Comment by bpetetot** [comment]
Good questions ;)
- how can I access the page for the private event I created?
> You will be able to access to the event page only if you know and have the event link. This link is available on the organizer event page.

- if I know the URL, can I still access a private event page?
> There is no control (yet), you only have to know the link.

- the filter that removes private events for the list looks like it lives in the front-end, which means I can override it if I want to; is that OK?
> Indeed, but I don't really know how to it otherwise, I could do with cloud functions, but functions can be long to start (about 10 seconds) If you have another idea to do it, I'm interested.

**Comment by hgwood** [comment]
@bpetetot Thanks for the answers ! For the third point you may be able to do it with firestore security rules.

**Pull request merged**
